post_install() {
    getent group sensors > /dev/null || groupadd -g 569 sensors
    getent passwd sensors > /dev/null || useradd -c 'Sensors daemon' -d /etc/sensors -s /usr/bin/nologin -g sensors -u 569 -g 569 sensors 
}

post_upgrade() {
    post_install $1
    usermod -u 569 sensors
    groupmod -g 569 sensors
}

post_remove() {
    post_install $1
    echo "You may want to remove sensors user and group"
}